import sys
import os
try:
    from schrodinger import structure
except ImportError:
    print "\n  Please run E:\\data\\virus\\maestro\\bin\\maestro_variable.bat\n"
    sys.exit(1)

def main(argv=sys.argv):
    if len(argv)!=4 and len(argv)!=5:
        print "\n  Usage: %s in.maegz out_protein out_ligands [N]"%argv[0]
        print "  in.maegz   : files generated by glide dock"
        print "  out_protein: protein in `in.maegz`."
        print "               can be pdb, maegz et al."
        print "  out_ligands: top `N` ligands sorted by `docking score`."
        print "               can be sdf, maegz et al."
        print "  [N]        : if not given, all ligands will be extracted!!\n"
        sys.exit(1)
    
    if len(argv) == 5:
        n = int(argv[4])
    else:
        n = 0
    inf = structure.StructureReader(argv[1])
    pro = inf.next()
    pro.write(argv[2])
    outf = structure.StructureWriter(argv[3])
    names = set()
    for ligand in inf:
        ligand.title = ligand.property['s_sd_IDNUMBER']
        if ligand.title not in names:
            names.add(ligand.title)
            outf.append(ligand)
        if n and (len(names) == n):
            break
    outf.close()

main()
