'''
#=============================================================================
#     FileName: same.py
#         Desc: 
#       Author: jlpeng
#        Email: jlpeng1201@gmail.com
#     HomePage: 
#      Created: 2014-03-24 13:37:10
#   LastChange: 2014-03-24 14:22:42
#      History:
#=============================================================================
'''
import sys

def main(argv=sys.argv):
    if len(argv) != 3:
        print "Usage: %s input1 input2"%argv[0]
        print "input1, input2: generated by `pmf_number_pairs.exe/py`"
        sys.exit(1)

    keys = set()

    inf1 = open(argv[1],"r")
    line = inf1.readline()
    line = inf1.readline()
    result1 = {}
    for line in inf1:
        line = line.split()
        result1[line[0]] = line[1:]
        keys.add(line[0])
    inf1.close()

    inf2 = open(argv[2],"r")
    line = inf2.readline()
    line = inf2.readline()
    result2 = {}
    for line in inf2:
        line = line.split()
        result2[line[0]] = line[1:]
        keys.add(line[0])
    inf2.close()

    for key in keys:
        if not result1.has_key(key):
            if all_0s(result2[key]):
                pass
                #print "%s: input1 miss; input2 0s"%key
            else:
                print "%s: input1 miss"%key
        elif not result2.has_key(key):
            if all_0s(result1[key]):
                pass
                #print "%s: input1 0s; input2 miss"%key
            else:
                print "%s: input2 miss"%key
        else:
            if len(result1[key]) != len(result2[key]):
                print "%s: different length"%key
            else:
                same = True
                for i in xrange(len(result1[key])):
                    if result1[key][i] != result2[key][i]:
                        same = False
                        break
                if not same:
                    print "%s: different content"%key



def all_0s(line):
    value = True
    for item in line:
        if item != "0":
            value = False
            break
    return value


main()

