'''
#=============================================================================
#     FileName: plot_potential.py
#         Desc: 
#       Author: jlpeng
#        Email: jlpeng1201@gmail.com
#     HomePage: 
#      Created: 2014-07-22 10:34:04
#   LastChange: 2014-07-22 10:48:53
#      History:
#=============================================================================
'''
import sys
import pickle
import dist
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import FormatStrFormatter

def main(argv=sys.argv):
    if len(argv) < 3:
        print "\n  Usage: %s potential.dat atom_pair[...]"%argv[0]
        print "\n  potential.dat: generated by 'calc_potential.py'"
        print "  atom_pair: should be PROTYPE_LIGTYPE, e.g. CF_CF"
        print ""
        sys.exit(1)

    inf = open(argv[1],"r")
    p = pickle.load(inf)
    inf.close()

    formatter = FormatStrFormatter("%.1f")

    for atom_pair in argv[2:]:
        ptype,ltype = atom_pair.split("_")
        index = dist.DC_TYPES.index(ltype+"-"+ptype)
        Aij_f = [item[0] for item in p.vect[index]]
        Aij = [item[1] for item in p.vect[index]]
        xs = [(dist.D_MIN+(k+1)*dist.D_DELT)*0.1 for k in xrange(len(Aij))]

        fig = plt.figure()

        ax = fig.add_subplot(111)
        ax.set_title(atom_pair)
        ax.plot(xs, Aij, c='b', marker='o', markersize=3., label='Aij(r)')
        ax.plot(xs, Aij_f, c='r', marker='v', markersize=3., label='Aij(r) f')
        ax.set_xlim(0., 12.)
        ax.set_xlabel("Atom Pair Potential", fontsize='small')
        ax.set_ylabel("PMF Score", fontsize='small')
        yticks = ax.get_yticks()
        ax.set_ylim(yticks[0], yticks[-1]+0.2)
        ax.xaxis.set_major_formatter(formatter)
        ax.yaxis.set_major_formatter(formatter)
        ax.legend(loc='upper right', numpoints=1)
        ax.axhline(y=0., xmin=0., xmax=12., color='black', alpha=0.7)

        plt.savefig(atom_pair+".tif", format="tif", dpi=150)


main()

