'''
#=============================================================================
#     FileName: pmf_score.py
#         Desc: 
#       Author: jlpeng
#        Email: jlpeng1201@gmail.com
#     HomePage: 
#      Created: 2014-08-14 16:10:33
#   LastChange: 2014-08-15 09:55:36
#      History:
#=============================================================================
'''
import sys
import os
import pickle
from glob import glob
import dist

global pts

def do_for_each(name, outf):
    global pts
    score = 0.
    inf = open(name,"r")
    for line in inf:
        ltype,lidx,ptype,pidx,d = line.strip().split(",")
        dc_type = "%s-%s"%(ltype,ptype)
        try:
            i = dist.DC_TYPES.index(dc_type)
            j = int((float(d) - dist.D_MIN*0.1) / dist.D_DELT * 10.)
            if float(d) >= 12.:
                continue
            score += pts.vect[i][j][0]
        except ValueError:
            print "Warning: %s contains dc_type %s not in dist.DC_TYPES"%(name, dc_type)
        except IndexError:
            print "d=%s, i=%d, j=%d"%(d,i,j)
            sys.exit(1)
    inf.close()
    print >>outf, "%s\t%.6f"%(name, score)

def main(argv=sys.argv):
    if len(argv) < 3:
        print "\n  Usage: %s outfile in.num[...]"%argv[0]
        print "  in.num: generated by pmf_atom_pairs.py"
        print ""
        sys.exit(1)

    if os.path.exists(argv[1]):
        print "Warning: %s already exists. Are you sure you've specified {outfile}?"%argv[1]
        sys.exit(1)
    dir = os.path.dirname(argv[0])
    dat_name = os.path.join(dir, "dist_splited_train_0525.dat")
    dc = dist.UnformatedInput(dat_name)
    global pts
    pts = dist.PTS(dc)

    outf = open(argv[1],"w")
    print >>outf, "name\tPMF.score"
    for name in argv[2:]:
        for each_name in glob(name):
            do_for_each(each_name, outf)
    outf.close()

main()

